
[package]
name = "bitcoin-tx-demo"
version = "0.1.0"
edition = "2021"

[dependencies]
bitcoin = "0.30.1"
bitcoincore-rpc = "0.17.0"
hex = "0.4.3"
rand = "0.8.5"
secp256k1 = { version = "0.27.0", features = ["rand"] }
